Add solidus_auth_devise gem and controllers
Fixes

    1) Accounts editing can edit an admin user
       Failure/Error: visit spree.login_path

       NoMethodError:
         undefined method `login_path' for #<Module:0x0000564d171694e0>
       # ./spec/features/account_spec.rb:7:in `block (3 levels) in <top (required)>'

Controllers needed in `lib/solidus_starter_frontend/engine.rb`.